function [rot, edges, vertices] = calcboundaries(b)
    rotdeg = b.rotation;
    rot = rotmat(deg2rad(rotdeg.roll), deg2rad(rotdeg.pitch), deg2rad(rotdeg.inhori));
    vertices_orig = [ -b.hw, -b.hw, -b.hl; ...
                      +b.hw, -b.hw, -b.hl; ...
                      -b.hw, +b.hw, -b.hl; ...
                      +b.hw, +b.hw, -b.hl; ...
                      -b.hw, -b.hw, +b.hl; ...
                      +b.hw, -b.hw, +b.hl; ...
                      -b.hw, +b.hw, +b.hl; ...
                      +b.hw, +b.hw, +b.hl; ];
    vertices = vertices_orig * rot';
    edges = [   toedge(1, 2), ...
                toedge(3, 4), ...
                toedge(5, 6), ...
                toedge(7, 8), ...
                toedge(1, 3), ...
                toedge(2, 4), ...
                toedge(5, 7), ...
                toedge(6, 8), ...
                toedge(1, 5), ...
                toedge(2, 6), ...
                toedge(3, 7), ...
                toedge(4, 8)    ];
    function lines = toedge(i1, i2)
        v1 = vertices(i1,:);
        v2 = vertices(i2,:);
        lines = {[v1(1) v2(1)], [v1(2) v2(2)], [v1(3) v2(3)]};
    end
end